import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import "./globals.css";
import Aoscompo from "@/utils/aos";
import NextTopLoader from 'nextjs-toploader';
import TopBar from "@/components/TopBar";
import ToasterContext from './api/contex/ToasetContex'
import { EditProvider } from './api/contex/EditContext'
import DownloadPDF from "@/components/DownloadPDF";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextTopLoader />
        <EditProvider>
          <Aoscompo>
            <TopBar />
            {children}
          </Aoscompo>
          <ToasterContext />
        </EditProvider>
        <DownloadPDF />
      </body>
    </html>
  );
}
